name: GlobalMarket
main: me.dasfaust.gm.Core
version: '2.0.0'
authors: ["Dasfaust", "Thatsmusic99"]
api-version: 1.13
permissions:
   globalmarket.use:
       default: true
   globalmarket.admin:
       default: op
depends: [ProtocolLib, Vault]
loadbefore: [GlobalMarketAdditions]